
import React, { useState, useRef } from 'react';
import { Role, Message } from '../types';
import { User, Bot, Download, Maximize2, Sparkles, Type, Check, X } from 'lucide-react';

interface ChatBubbleProps {
  message: Message;
  onUpdateMessage?: (messageId: string, updatedContent: any[]) => void;
}

const ChatBubble: React.FC<ChatBubbleProps> = ({ message, onUpdateMessage }) => {
  const isAgent = message.role === Role.AGENT;
  const [editingImageIdx, setEditingImageIdx] = useState<number | null>(null);
  const [overlayText, setOverlayText] = useState('');
  const [overlayPos, setOverlayPos] = useState<'top' | 'center' | 'bottom'>('bottom');

  const handleDownload = (url: string) => {
    const link = document.createElement('a');
    link.href = url;
    link.download = `nano-banana-gen-${Date.now()}.png`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const applyTextOverlay = async (idx: number, originalSrc: string) => {
    if (!overlayText.trim()) {
      setEditingImageIdx(null);
      return;
    }

    const img = new Image();
    img.crossOrigin = "anonymous";
    img.src = originalSrc;
    
    await new Promise((resolve) => {
      img.onload = resolve;
    });

    const canvas = document.createElement('canvas');
    canvas.width = img.width;
    canvas.height = img.height;
    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    ctx.drawImage(img, 0, 0);

    const fontSize = Math.floor(canvas.width * 0.06);
    ctx.font = `bold ${fontSize}px Inter, sans-serif`;
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';
    
    ctx.shadowColor = "rgba(0, 0, 0, 0.8)";
    ctx.shadowBlur = 10;
    ctx.lineWidth = 4;
    ctx.strokeStyle = "black";
    ctx.fillStyle = "white";

    let x = canvas.width / 2;
    let y = canvas.height / 2;

    if (overlayPos === 'top') y = fontSize * 1.5;
    if (overlayPos === 'bottom') y = canvas.height - (fontSize * 1.5);

    ctx.strokeText(overlayText, x, y);
    ctx.fillText(overlayText, x, y);

    const newImageData = canvas.toDataURL('image/png');
    
    if (onUpdateMessage) {
      const newContent = [...message.content];
      newContent[idx] = { ...newContent[idx], image: newImageData };
      onUpdateMessage(message.id, newContent);
    }

    setEditingImageIdx(null);
    setOverlayText('');
  };

  return (
    <div className={`flex w-full mb-6 ${isAgent ? 'justify-start' : 'justify-end'} animate-elastic-reveal`}>
      <div className={`flex max-w-[85%] md:max-w-[70%] ${isAgent ? 'flex-row' : 'flex-row-reverse'}`}>
        <div className={`flex-shrink-0 w-10 h-10 rounded-full flex items-center justify-center transition-glass ${
          isAgent ? 'bg-yellow-400 text-black shadow-[0_0_15px_rgba(250,204,21,0.2)] mr-3' : 'bg-white/10 text-white ml-3'
        }`}>
          {isAgent ? <Bot size={20} /> : <User size={20} />}
        </div>

        <div className="flex flex-col space-y-2">
          {message.content.map((part, idx) => (
            <div key={idx} className={`relative group`}>
              {part.text && (
                <div className={`px-4 py-3 rounded-2xl text-sm leading-relaxed transition-glass ${
                  isAgent 
                    ? 'bg-white/5 border border-white/10 text-gray-200 shadow-sm' 
                    : 'banana-gradient text-black font-medium shadow-lg shadow-yellow-400/10'
                }`}>
                  {part.text}
                </div>
              )}
              
              {part.image && (
                <div className="relative overflow-hidden rounded-2xl border border-white/10 mt-2 shadow-2xl group/img animate-reveal-blur">
                  <img 
                    src={part.image} 
                    alt="Generated by Nano Banana" 
                    className="w-full h-auto object-cover max-h-[500px] transition-all duration-1000 group-hover/img:scale-[1.05]" 
                  />
                  
                  {/* Image Badge */}
                  <div className="absolute top-3 left-3 px-2 py-1 glass rounded-lg flex items-center space-x-1.5 opacity-0 group-hover/img:opacity-100 transition-all duration-300 translate-y-1 group-hover/img:translate-y-0">
                    <Sparkles size={12} className="text-yellow-400 animate-pulse" />
                    <span className="text-[10px] font-bold text-white/80 uppercase tracking-tighter">Nano Vision</span>
                  </div>

                  {/* Action Overlay */}
                  <div className={`absolute inset-0 bg-black/40 opacity-0 group-hover/img:opacity-100 transition-all duration-300 flex items-center justify-center space-x-4 ${editingImageIdx === idx ? 'hidden' : ''}`}>
                    <button 
                      onClick={() => setEditingImageIdx(idx)}
                      className="p-3 bg-white/10 backdrop-blur-xl rounded-full text-white hover:bg-yellow-400 hover:text-black transition-all transform translate-y-4 group-hover/img:translate-y-0 hover:scale-110 active:scale-90"
                      title="Add Text Overlay"
                    >
                      <Type size={20} />
                    </button>
                    <button 
                      onClick={() => handleDownload(part.image!)}
                      className="p-3 bg-white/10 backdrop-blur-xl rounded-full text-white hover:bg-yellow-400 hover:text-black transition-all transform translate-y-4 group-hover/img:translate-y-0 delay-75 hover:scale-110 active:scale-90"
                    >
                      <Download size={20} />
                    </button>
                    <button className="p-3 bg-white/10 backdrop-blur-xl rounded-full text-white hover:bg-yellow-400 hover:text-black transition-all transform translate-y-4 group-hover/img:translate-y-0 delay-100 hover:scale-110 active:scale-90">
                      <Maximize2 size={20} />
                    </button>
                  </div>

                  {/* Text Overlay Editor */}
                  {editingImageIdx === idx && (
                    <div className="absolute inset-0 flex flex-col items-center justify-center p-6 bg-black/80 backdrop-blur-md z-10 animate-reveal-blur">
                      <div className="w-full max-w-xs space-y-4">
                        <div className="flex items-center justify-between mb-2">
                           <span className="text-xs font-bold text-yellow-400 uppercase tracking-widest">Text Overlay</span>
                           <button onClick={() => setEditingImageIdx(null)} className="text-white/40 hover:text-white transition-colors"><X size={16}/></button>
                        </div>
                        
                        <input 
                          autoFocus
                          type="text"
                          value={overlayText}
                          onChange={(e) => setOverlayText(e.target.value)}
                          placeholder="Type your message..."
                          className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-3 text-white text-sm focus:ring-1 focus:ring-yellow-400 outline-none transition-all"
                        />

                        <div className="flex items-center justify-center space-x-2">
                          {(['top', 'center', 'bottom'] as const).map((pos) => (
                            <button
                              key={pos}
                              onClick={() => setOverlayPos(pos)}
                              className={`flex-1 py-2 text-[10px] font-bold uppercase rounded-lg border transition-all duration-300 ${
                                overlayPos === pos 
                                  ? 'bg-yellow-400 border-yellow-400 text-black shadow-[0_0_15px_rgba(250,204,21,0.3)]' 
                                  : 'bg-white/5 border-white/10 text-white/40 hover:text-white hover:bg-white/10'
                              }`}
                            >
                              {pos}
                            </button>
                          ))}
                        </div>

                        <button 
                          onClick={() => applyTextOverlay(idx, part.image!)}
                          className="w-full py-3 banana-gradient rounded-xl text-black text-sm font-bold shadow-lg shadow-yellow-400/20 flex items-center justify-center space-x-2 active:scale-95 transition-transform"
                        >
                          <Check size={18} />
                          <span>Apply Overlay</span>
                        </button>
                      </div>
                    </div>
                  )}
                </div>
              )}
            </div>
          ))}

          {message.isPending && (
            <div className="flex items-center space-x-2 mt-1 px-2 animate-reveal-blur">
              <div className="flex space-x-1.5">
                <div className="w-1.5 h-1.5 bg-yellow-400 rounded-full animate-bounce" style={{ animationDelay: '0ms' }} />
                <div className="w-1.5 h-1.5 bg-yellow-400 rounded-full animate-bounce" style={{ animationDelay: '200ms' }} />
                <div className="w-1.5 h-1.5 bg-yellow-400 rounded-full animate-bounce" style={{ animationDelay: '400ms' }} />
              </div>
              <span className="text-[10px] text-yellow-400/50 uppercase font-bold tracking-[0.2em]">Nano Synthesis</span>
            </div>
          )}
          
          <span className={`text-[10px] text-white/30 ${isAgent ? 'text-left' : 'text-right'} opacity-0 animate-reveal-blur`} style={{ animationDelay: '0.4s' }}>
            {message.timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
          </span>
        </div>
      </div>
    </div>
  );
};

export default ChatBubble;
